auto: true
server: true
paginate: 4
exclude: README.md, .gitignore
permalink: '/:year/:month/:title' 
description: 'Online Presence of Adrian Rossouw'
baseurl: http://vertice.github.com/daemon-co-za/
siteName: 'Daemon.co.za'
github_login: 'Vertice'
github_repo: 'daemon-co-za'
github_language: 'JavaScript'
