paginate: 8
exclude:
  - README.md
  - .gitignore
  - bower_components
  - node_modules
  - package.json
  - bower.json
permalink: '/:year/:month/:title' 
description: 'Online Presence of Adrian Rossouw'
baseurl: http://daemon.co.za/
siteName: 'Daemon.co.za'
github_login: 'Vertice'
github_repo: 'daemon-co-za'
github_language: 'JavaScript'
excerpt_separator: '<!--more-->'
markdown: kramdown
